spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper.generator/*.xml
  global-config:
    db-config:
      id-type: auto